### ISSUE TITLE
Unreadable files/directories lead to a crash, not a note in the results

### ISSUE THREAD

**Issue by superian** [binsento42/Cathy#7]
At the moment, if there is a file or directory where the user does not have 'read' permission, something like the following happens:

me@pc:~/Cathy-main$ python3 cathy.py scan /media/me/My\ Book/
Scanning: /media/me/My Book ...
Traceback (most recent call last):
  File "/home/me/Cathy-main/cathy.py", line 658, in <module>
    cat = CathyCat.scan(scanpath)
  File "/home/me/Cathy-main/cathy.py", line 567, in scan
    t_cat.info.append(t_cat.scandir(0, start_path))
  File "/home/me/Cathy-main/cathy.py", line 539, in scandir
    (did, fcnt, tsiz) = self.scandir(keepdir, elem)
  File "/home/me/Cathy-main/cathy.py", line 539, in scandir
    (did, fcnt, tsiz) = self.scandir(keepdir, elem)
  File "/home/me/Cathy-main/cathy.py", line 539, in scandir
    (did, fcnt, tsiz) = self.scandir(keepdir, elem)
  [Previous line repeated 5 more times]
  File "/home/me/Cathy-main/cathy.py", line 526, in scandir
    for el in os.listdir(start_path):
PermissionError: [Errno 13] Permission denied: '/media/me/My Book/Core2home/.google/picasa/3.0/dosdevices/z:/tmp/systemd-private-774a0ba670754d1fb3a141d9747bc7dc-systemd-logind.service-ieuL7m'

So you either have to run as root, leading to the results being owned by root, or alter the file/directory permissions, which may have Consequences if you need them in the future.

Ubuntu 22.04 so Python 3.10.6

**Comment by gostlund** [comment]
I worked around this with a try block inside the scandir function:

        def scandir(self, dir_id, start_path):
        # the recursive function for scanning a disk
        # it is better to do the recursion yourself instead of using os.walk,
        # because then you can build the Cathy tree more easily (filecount and dirsize)
        tsize = 0
        tsiz = 0
        filecnt = 0
        fcnt = 0
        try:
            for el in os.listdir(start_path):
                elem = os.path.join(start_path, el)
                if os.path.isfile(elem):
                    filecnt = filecnt + 1
                    cursize = os.path.getsize(elem)
                    tsize = tsize + cursize
                    dat = os.path.getmtime(elem)
                    self.elm.append((int(dat), cursize, dir_id, el))
                if os.path.isdir(elem):
                    self.totaldirs = self.totaldirs + 1
                    keepdir = self.totaldirs
                    dat = os.path.getmtime(elem)
                    self.elm.append((int(dat), -keepdir, dir_id, el))
                    (did, fcnt, tsiz) = self.scandir(keepdir, elem)
                    self.info.append((keepdir, fcnt, tsiz))
                filecnt = filecnt + fcnt
                tsize = tsize + tsiz
        except PermissionError as e:
            print(e)
        return (dir_id, filecnt, tsize)


I'm sure someone could incorporate this into a PR at some point, I didn't have the time, but wanted this here for future reference in case I needed it again at least.
